api/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("getip/",get_ip,name="api-getip"),
    path("whois/",whois,name="api-whois"),
    path("ssl_certificate/",ssl_certificate, name="api-ssl-certificate"),
    path("wappalyzer/",wappalyzer,name="api-wappalyzer"),
    path("nmap_port/",nmap_port,name="api-nmap"),
    path("dns_enum/",dns_enum,name="api-dns-enum"),
    path("dns_for_family/",dns_for_family,name="api-dns-for-family"),
    path("subdomain_enum/",subdomain_enum,name="api-subdomain-enum"),   
    path("os_scan/",osscan,name="api-os-scan"),
    path("GenerateReport/",GenerateReport, name="GenerateReport"),

]

godseye/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("user.urls")),
    path("api/", include("api.urls")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("scan/", scan, name="scan"),
    path("spoor/<str:case_number>", spoor, name="spoor"),
    path("email_header_analyse", analyse_header, name="email-header-analyse"),
    path("malware_analysis", malware_analysis, name="malware-analysis"),
    path("image_analysis/", image_analysis, name="image_analysis"),
    path("GenerateReport/", GenerateReport, name="GenerateReport"),
]

user/models.py
from django.db import models

class Case(models.Model):
    case_number = models.CharField(max_length=5,unique=True)
    domain = models.CharField(max_length=50,null=True,blank=True)
    link = models.CharField(max_length=255,null=True,blank=True)
    is_family = models.BooleanField(default=False)
    ip_address = models.CharField(max_length=20,null=True,blank=True)
    
class WhoIs(models.Model):
    case_obj = models.OneToOneField(Case,on_delete=models.CASCADE,related_name="related_whois_details")
    res = models.JSONField(null=True,blank=True)


class SslCertificate(models.Model):
    case_obj = models.OneToOneField(Case,on_delete=models.CASCADE,related_name="related_sslcertificate_details")
    res = models.JSONField(null=True,blank=True)


class WappalyzerModel(models.Model):
    case_obj = models.OneToOneField(Case,on_delete=models.CASCADE,related_name="related_wappalyzer_details")
    res = models.JSONField(null=True,blank=True)


class NmapPort(models.Model):
    case_obj = models.OneToOneField(Case,on_delete=models.CASCADE,related_name="related_nmap_port_details")
    res = models.JSONField(null=True,blank=True)


class DnsEnum(models.Model):
    case_obj = models.OneToOneField(Case,on_delete=models.CASCADE,related_name="related_dns_enum_details")
    res = models.JSONField(null=True,blank=True)


class SubDomain(models.Model):
    case_obj = models.OneToOneField(Case,on_delete=models.CASCADE,related_name="related_subdomain_details")
    res = models.JSONField(null=True,blank=True)
    
            
class WhatCms(models.Model):
    case_obj = models.OneToOneField(Case,on_delete=models.CASCADE,related_name="related_whatcms_details")
    res = models.JSONField(null=True,blank=True)
                

class MalwareFile(models.Model):
    # case_obj = models.ForeignKey(Case,on_delete=models.CASCADE,related_name="related_malware_files")
    case_number = models.CharField(max_length=5)
    malware_file = models.FileField(upload_to="media/")
    
class OsScan(models.Model):
    case_obj = models.OneToOneField(Case,on_delete=models.CASCADE,related_name="related_os_scan_details")
    res = models.JSONField(null=True,blank=True)


class ImageAnalysis(models.Model):
    # case_obj = models.ForeignKey(
    #     Case, on_delete=models.CASCADE, related_name="image_files")
    image_file = models.FileField(upload_to="exifImages/")

user/forms.py
from django import forms
from .models import *


class CaseCreationForm(forms.ModelForm):
    class Meta:
        model = Case
        fields = ["case_number","domain","link"]
        def clean(self):
            cleaned_data=super().clean()
            
            case_number = cleaned_data.get('case_number')
            domain = cleaned_data.get('domain')
            link = cleaned_data.get('link')
    
            if len(case_number) == 0:
                 raise forms.ValidationError("Enter valid Data")

            if len(domain) == 0:
                 raise forms.ValidationError("Enter valid Domain")

            if len(link) == 0 :
                 raise forms.ValidationError("Enter valid Link")

            if Case.objects.filter(case_number=case_number).exists():
                 raise forms.ValidationError("Case Number Already Exists")
            print("cretaipon endyfbujerbghkv:")
            return cleaned_data

class CaseSearchForm(forms.ModelForm):
    class Meta:
        model = Case
        fields = ["case_number"]
        def clean(self):
            cleaned_data = super().clean()
            
            case_number = cleaned_data.get('case_number')
        
            if len(case_number) == 0:
                 raise forms.ValidationError("Enter valid Data")

            if not Case.objects.filter(case_number=case_number).exists():
                 raise forms.ValidationError("Case Number Does Not Exists")
            print("searcg endyfbujerbghkv:")

            return cleaned_data
'''

class CaseCreationForm(forms.ModelForm):
    class Meta:
        model = Case
        fields = ["case_number","domain","link"]

class CaseSearchForm(forms.ModelForm):
    class Meta:
        model = Case
        fields = ["case_number"]
        '''


class MalwareUploadForm(forms.Form):
    # class Meta:
    #     model = Case
    #     fields = ["case_number","malware_file"]
    case_number = forms.CharField(max_length=5)
    malware_file = forms.FileField()

class ImageUploadForm(forms.Form):
    image_file = forms.ImageField()

user/views.py
import hashlib
import json
import subprocess
from virus_total_apis import PublicApi as VirusTotalPublicApi
from http.client import HTTPResponse
from django.shortcuts import render, redirect
from .forms import *
from email.parser import HeaderParser
import time
import dateutil.parser
from io import BytesIO
from django.http import HttpResponse
from django.template.loader import get_template
from datetime import datetime
import re
from xhtml2pdf import pisa
import Exif
from exif import Image
import exifread
from io import BytesIO
from .models import Case
import hashlib
from virus_total_apis import PublicApi as VirusTotalPublicApi



def dashboard(request):
    return render(request, "user/welcome.html")

# def search(request):

#     if request.method == "POST":
#         print("Entered search in view")
#         searchForm = CaseSearchForm(request.POST)
#         print("Seaarch Form", searchForm.is_valid())

#         if searchForm.is_valid():    
#             case_number = searchForm.cleaned_data["case_number"]
#             print("success in Search:",case_number)
#             return redirect("spoor", case_number)
#     else:
#         return render(request, "user/search.html",{"searchForm":CaseSearchForm()})
        
# def scan(request):
#     if request.method == "POST":
#         creationForm = CaseCreationForm(request.POST)
#         print("Creation Form", creationForm.is_valid())
#         searchForm= CaseSearchForm(request.POST)
#         print("Seaarch Form", searchForm.is_valid())
        
    
#         if creationForm.is_valid():
#             creationForm.save()
#             case_number = creationForm.cleaned_data["case_number"]
#             print("success in creation:",case_number)
#             return redirect("spoor", case_number)
#         elif not searchForm.is_valid() and not creationForm.is_valid():
#             if not creationForm.is_valid():
#                  return render(request, "user/scan.html", {
#                 "creationForm":creationForm, "searchForm":CaseSearchForm()})
#             elif not searchForm.is_valid():
#                  return render(request, "user/scan.html", {
#                 "creationForm":CaseCreationForm(), "searchForm":searchForm})
    
#     if request.method =='GET':
#         searchForm = CaseSearchForm()
#         creationForm = CaseCreationForm()
#         return render(request, "user/scan.html", {
#                 "creationForm":creationForm, "searchForm":searchForm})

def scan(request):
    if request.method=='POST':
        if 'form1_submit' in request.POST:
            creation_case_number = request.POST.get('creation_case_number')
            creation_domain = request.POST.get('creation_domain')
            creation_link = request.POST.get('creation_link')
            if Case.objects.filter(case_number=creation_case_number).exists():
                return render(request,'user/scan.html',{"error_message":"Case Number Already Exist"})
            else:
                creation_data = {
                'case_number': creation_case_number,
                'domain': creation_domain,
                'link':creation_link,
                }
                Case.objects.create(**creation_data)
                return redirect("spoor",creation_case_number)

        elif 'form2_submit' in request.POST:
            search_case_number = request.POST.get('search_case_number')
            if not Case.objects.filter(case_number=search_case_number).exists():
                return render(request,'user/scan.html',{"error_message":"Case Number Does Not Exist"})
            
            else:
                return redirect("spoor",search_case_number)
            
    return render(request, 'user/scan.html')


def spoor(request, case_number):
    case_obj = Case.objects.get(case_number=case_number)
    return render(request, "user/spoor.html", {
        "domain": str(case_obj.domain),
        "url": str(case_obj.link),
        "case_number": case_obj.case_number
    })


def dateParser(line):
    try:
        r = dateutil.parser.parse(line, fuzzy=True)
    except ValueError:
        r = re.findall('^(.*?)\s*(?:\(|utc)', line, re.I)
        if r:
            r = dateutil.parser.parse(r[0])
    return r


def utility_processor():
    def getCountryForIP(line):
        ipv4_address = re.compile(r"""
            \b((?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d|\d)\.
            (?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d|\d)\.
            (?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d|\d)\.
            (?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d|\d))\b""", re.X)
        ip = ipv4_address.findall(line)
        if ip:
            ip = ip[0]  # take the 1st ip and ignore the rest
            if IP(ip).iptype() == 'PUBLIC':
                r = reader.country(ip).country
                if r.iso_code and r.name:
                    return {
                        'iso_code': r.iso_code.lower(),
                        'country_name': r.name
                    }
    return dict(country=getCountryForIP)


def getHeaderVal(h, data, rex='\s*(.*?)\n\S+:\s'):
    r = re.findall('%s:%s' % (h, rex), data, re.X | re.DOTALL | re.I)
    if r:
        return r[0].strip()
    else:
        return None


def email_header(header):
    mail_data = header
    r = {}
    n = HeaderParser().parsestr(mail_data)
    received = n.get_all('Received')
    if received:
        received = [i for i in received if ('from' in i or 'by' in i)]
    else:
        received = re.findall(
            'Received:\s*(.*?)\n\S+:\s+', mail_data, re.X | re.DOTALL | re.I)
    c = len(received)
    for i in range(len(received)):
        if ';' in received[i]:
            line = received[i].split(';')
        else:
            line = received[i].split('\r\n')
        line = list(map(str.strip, line))
        line = [x.replace('\r\n', ' ') for x in line]
        try:
            if ';' in received[i + 1]:
                next_line = received[i + 1].split(';')
            else:
                next_line = received[i + 1].split('\r\n')
            next_line = list(map(str.strip, next_line))
            next_line = [x.replace('\r\n', '') for x in next_line]
        except IndexError:
            next_line = None

        if line[0].startswith('from'):
            data = re.findall(
                """
                from\s+
                (.*?)\s+
                by(.*?)
                (?:
                    (?:with|via)
                    (.*?)
                    (?:\sid\s|$)
                    |\sid\s|$
                )""", line[0], re.DOTALL | re.X)
        else:
            data = re.findall(
                """
                ()by
                (.*?)
                (?:
                    (?:with|via)
                    (.*?)
                    (?:\sid\s|$)
                    |\sid\s
                )""", line[0], re.DOTALL | re.X)

    summary = {
        'From': n.get('From') or getHeaderVal('from', mail_data),
        'To': n.get('to') or getHeaderVal('to', mail_data),
        'Cc': n.get('cc') or getHeaderVal('cc', mail_data),
        'Subject': n.get('Subject') or getHeaderVal('Subject', mail_data),
        'MessageID': n.get('Message-ID') or getHeaderVal('Message-ID', mail_data),
        'Date': n.get('Date') or getHeaderVal('Date', mail_data),
    }
    # ips = set(re.findall( r'[0-9]+(?:\.[0-9]+){3}', mail_data ))
    ips = set(re.findall(r'(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})', mail_data))
    emails = re.findall(r"[a-z0-9\.\-+_]+@[a-z0-9\.\-+_]+\.[a-z]+", mail_data)
    regex = r"(?i)\b((?:https?://|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'\".,<>?«»“”‘’]))"
    urls = re.findall(regex, mail_data)

    security_headers = ['Received-SPF', 'Authentication-Results',
                        'DKIM-Signature', 'ARC-Authentication-Results']

    data = {
        "ips": ips,
        "emails": emails,
        "urls": urls,
        "security_headers": security_headers,
        "summary": summary,
        "n": n
    }
    return data


def analyse_header(request):
    if request.method == "POST":
        header = request.POST.get("header")
        data = email_header(header)
        # print("asdfasdfasdf",type(data["n"]))
        request.session['emailheader'] = header
        return render(request, "user/analyse_header.html", {
            "header" : header,
            "summary": data["summary"],
            "ips": data["ips"],
            "urls": data["urls"],
            "emails": set(data["emails"]),
            "is_true": True

        })

    return render(request, "user/analyse_header.html")


def malware_analysis(request):
    if request.method == "POST":
        print(request.FILES)
        form = MalwareUploadForm(request.POST, request.FILES)
        print(form.is_valid())
        if form.is_valid():
            case_number = form.cleaned_data.get("case_number")
            file = form.cleaned_data.get("malware_file")
            # case_obj = Case.objects.get_or_create(case_number=case_number)
            mal_obj = MalwareFile.objects.create(case_number=case_number, malware_file=file)
            print(mal_obj.malware_file.path)
            mal_obj.save()
            file_type_output = subprocess.run(["/home/falcon/Desktop/Git Repo/Final-Year-Project/Feb/Spoor/user/filetype.sh", mal_obj.malware_file.path], capture_output=True)
            file_type_output = file_type_output.stdout
            file_type_output = file_type_output.decode('ascii')

            hashing_output = subprocess.run(["/home/falcon/Desktop/Git Repo/Final-Year-Project/Feb/Spoor/user/hashing.sh", mal_obj.malware_file.path], capture_output=True)
            hashing_output = hashing_output.stdout
            hashing_output = hashing_output.decode('ascii')

            hash_ = hashing_output[10:51]

            
            API_KEY = "b47c1974a73b366eb24810ab6b2855e10ab86a022c311f891bf1ec5bf9d83a24"
            
            EICAR = hash_.encode('utf-8')

user/templates/user/analyse_header.html
{% extends 'user/index.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="container" style="text-align: center;" >
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div
            class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Email Header Analyse</h6>   
        </div>
        <!-- Card Body -->
        <div class="card-body" style="display:block ;">
            <form action="email_header_analyse" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="exampleFormControlTextarea1">Enter Email Header  </label>
                    <textarea name ="header" class="form-control" id="exampleFormControlTextarea1" rows="17"></textarea>
                  </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            <style>

                #lable {
                  display: block;
                  width: 100%;
                  height: 400px;  
            
                }

                input[type="file"] label{                  
                  display: block;
                  width: 100px;
                  height: 100px;
                }

                #exampleFormControlTextarea1{
                    
                    background-image: url({% static 'images/mail.svg'%});
                    background-position: center center;
                    background-repeat: no-repeat;
                    background-size: fit;
                    padding: 10px;
                    border: none;
                    width: 100%;
                    height: 100%;
                    opacity: 0.2;
                    margin-left: auto;
                    margin-right: auto;
                    border: 1px solid black;

                }

              </style>
        </div>
    </div>
</div>
{% if is_true %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Summary</h6>
                </div>
                <div class="card-body overflow-auto" style="max-height:350px">
                    <div class="table-responsive">
                        <table class="table table-bordered" width="100%" cellspacing="0">
                            <thead>
                            
                            </thead>
                            <tbody>
                                {% for key,value in summary.items %}
                                <tr>
                                    <td>{{key}}</td>
                                    <td>{{value}}</td>
                                </tr>
                                {% endfor%}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Emails Mentioned</h6>
                </div>
                <div class="card-body overflow-auto" style="max-height:350px" >
                    <div class="table-responsive">
                        <table class="table table-bordered" width="100%" cellspacing="0" >
                            
                            <tbody>
                                {% for email in emails %}
                                <tr>
                                    <td>{{email}}</td>
                                </tr>
                                {% endfor%}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Ip's Mentioned</h6>
                </div>
                <div class="card-body overflow-auto" style="max-height:350px">
                    <div class="table-responsive">
                        <table class="table table-bordered" width="100%" cellspacing="0" >
                            <thead>
                            
                            </thead>
                            <tbody>
                                {% for ip in ips %}
                                <tr>
                                    <td>{{ip}}</td>
                                </tr>
                                {% endfor%}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Urls Mentioned</h6>
                </div>
                <div class="card-body overflow-auto" style="max-height:350px">
                    <div class="table-responsive">
                        <table class="table table-bordered" width="100%" cellspacing="0">
                            <thead>
                            
                            </thead>
                            <tbody>
                                {% for url in urls %}
                                <tr>
                                    <td>{{url.0}}</td>
                                </tr>
                                {% endfor%}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="py-2 text-right mx-4">
    <a href="/GenerateReport/">
        <button type="submit" class="btn btn-primary">Download
        </button></a> 
    </div>

{% endif %}

{% endblock %}

user/templates/user/image_analysis.html
{% extends 'user/index.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<style>
    input[type="text"] {
        /* display: block; */
        width: 68vw;
        margin: 15px;
    }

    label {
        display: block;
        margin: 15px;
        text-align: left;
    }
</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
    integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<div class="container" style="text-align: center;">
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Image Analyse</h6>
        </div>
        <!-- Card Body -->
        <div class="card-body" style="display:block ;">
            <form action="" method="post" enctype='multipart/form-data'>
            
                {% csrf_token %}
                <label for="id_image_file" id="lable" style="object-fit: contain;"><img src={% static 'images/upload.svg'%} alt="Upload"></label>
                {{form|crispy}}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            <style>

                #lable {
                  display: block;
                  width: 100%;
                  height: 400px;  
            
                }


                #lable img{
                  display: block;
                  width: 100%;
                  height: 100%;  
                  margin-left: auto;
                  margin-right: auto;
                }

                input[type="image"] {
                  
                  display: block;
                  width: 100px;
                  height: 100px;
                  position: absolute;
  opacity: 0;
  pointer-events: none;
                  
                }
              </style>
        </div>
    </div>
</div>
{% if exif_data.is_true %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Summary</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" width="100%" cellspacing="0">
                            <thead>

                            </thead>
                            <tbody>
                                <tr>
                                    <td>Name</td>
                                    <td>{{exif_data.FileName}}</td>
                                </tr>
                                <tr>
                                    <td>DateTime</td>
                                    <td>{{exif_data.DateTime}}</td>
                                </tr>
                                <tr>
                                    <td>Make</td>
                                    <td>{{exif_data.Make}}</td>
                                </tr>
                                <tr>
                                    <td>Model</td>
                                    <td>{{exif_data.Model}}</td>
                                </tr>

                                <tr>
                                    <td>GPS Info</td>
                                    <td>{{exif_data.GPSInfo}}</td>
                                </tr>
                                <tr>
                                    <td>Latitude</td>
                                    <td>{{exif_data.latitude}}</td>
                                </tr>

                                <tr>
                                    <td>Longitude</td>
                                    <td>{{exif_data.longitude}}</td>
                                </tr>
                                <tr>
                                    <td>Locate</td>
                                    <a href="{{exif_data.map_link}}"></a><td>{{exif_data.map_link}}</td>
                                </tr>
                                <tr>
                                    <td>Image Height</td>
                                    <td>{{exif_data.ImageHeight}}</td>
                                </tr>

                                <tr>
                                    <td>Image Width</td>
                                    <td>{{exif_data.ImageWidth}}</td>
                                </tr>

                                <tr>
                                    <td>Image Format</td>
                                    <td>{{exif_data.ImageFormat}}</td>
                                </tr>

                                <tr>
                                    <td>Is Animated</td>
                                    <td>{{exif_data.IsAnimated}}</td>
                                </tr>
                             
                            </tbody>
                            <!-- <tbody>

                                {% if exif_data %}
                                <ul>
                                    {% for key, value in my_dict.items %}
                                    <td>{{ key }}</td> 
                                    <td>{{ value }}</td>
                                    {% endfor %}
                                </ul>
                                {% else %}
                                <p>The dictionary is empty.</p>
                                {% endif %}

                            </tbody> -->
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}




{% endblock %}

user/templates/user/scan1.html
{% extends 'user/index.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <style>
    input[type="text"]{
        display: block;
        width: 97%;
        margin: 15px;
    }
    label{
        display: block;
        margin: 15px;
        text-align: left;
    }

    </style>

 

<div style="display: flex;">
<div class="container" style="text-align: center; width: 50%;" >
    <div class="text">

        {% if creationForm.errors %}
        <ul>
        {% for field, errors in creationForm.errors.items %}
        <li>{{ field }}:</li>
        <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
        </ul>
        {% endfor %}
        </ul>
        {% endif %}
        </div>
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div
            class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Scan</h6>   
        </div>
        <!-- Card Body -->
        <div class="card-body" style="display:block ; ">
            <form action="" method="POST">
                {% csrf_token %}
                {{ creationForm|crispy }}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>


<div class="container" style="text-align: center; width: 50%;" >
    <div class="text">

        {% if searchForm.errors %}
        <ul>
        {% for field, errors in searchForm.errors.items %}
        <li>{{ field }}:</li>
        <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
        </ul>
        {% endfor %}
        </ul>
        {% endif %}
        </div>
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div
            class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Search Cases </h6>   
        </div>
        <!-- Card Body -->
        <div class="card-body" style="display:block ;">
            <form action="" method="POST">
                {% csrf_token %}
                {{ searchForm|crispy }}

                <!-- <input type="text" name="case_number" maxlength="5" class="textinput textInput" required="" id="id_case_number"> -->
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>

</div>


{% endblock %}